### ISSUE TITLE
Display version number in `configname`

### ISSUE THREAD

**Issue by msh100** [msh100/ETPro-configs#17]
Display version number and change colour for new config set.

**Comment by ohurcool** [comment]
current:

[Msh100] "^3Global ^w1on1 ^dConfig"

my ideas:

[ohurcool] "^?Global ^71on1 ^0Config ^1v2.0"
[ohurcool] "^>Global ^71on1 ^4Config ^0v2.0"
[ohurcool] maybe one of those or a variation of one
[ohurcool] keep the format white probably and the version number black/white maybe
[ohurcool] then just 2 nice looking colors for global config

**Comment by msh100** [comment]
![](http://entirely.pro/img/1432385179-32Rg.png)
^?Global ^71on1 ^0Config ^1v2.0

![](http://entirely.pro/img/1432385206-bdsR.png)
^>Global ^71on1 ^4Config ^0v2.0

![](http://entirely.pro/img/1432385292-viKK.png)
^3Global ^71on1 ^3Config ^2v2.0

I think the colours in the ones you mentioned look quite dark and unclear. I have tried basic lighter colours, what do you think?

**Comment by Swanidius** [comment]
I prefer 
^3Global ^71on1 ^3Config ^2v2.0

much more clear

**Comment by ohurcool** [comment]
ye it's fine, maybe make either Global or Config a different color though

"^5Global ^71on1 ^3Config ^2v2.0"
"^3Global ^71on1 ^5Config ^2v2.0"

**Comment by msh100** [comment]
![](http://entirely.pro/img/1432403717-Rbb0.png)
^5Global ^71on1 ^3Config ^2v2.0

![](http://entirely.pro/img/1432403758-LeOi.png)
^3Global ^71on1 ^5Config ^2v2.0

Both of these also work, I guess I favour the first
