### ISSUE TITLE
Vote map fix

### ISSUE THREAD

**Issue by miraya** [msh100/ETPro-configs#26]
globalcombined.lua callvote map fix
Any idea why the version3 fix was reverted to the version2 fix by Perlo_0ung?! ?

As far as I know when you load a config and vote a map this way: callvote map Supply what happens next is this -> Server map Supply; ETPro cannot find Supply in map hashes thus unloads config, globalcombined.lua: ref map supply; It will fix the issue of the map but it requires you to vote the config again, unnecessary in my opinion and should've kept  the modified fix.

P.S: Can anyone confirm if this fixed? Last time I tested this was in 2012 haven't encoutered this issue after that.

**Comment by ohurcool** [comment]
the current config fixes it automatically without needing to callvote the config

**Comment by msh100** [comment]
In which case this needs testing with the current script in `master`.

**Comment by miraya** [comment]
@ohurcool do you mean the current 1.3 release or the 2.0 master ?
I'm going on a hunch and say you are talking about 1.3 release, if so, yes cause that one has the fix I modified in order to launch the config after voting the correct map, but in the master branch the globalcombined.lua has omitted this fix for some reason, therefore I suggest we commit the correct fix back.

Edit: After thoroughly testing I've come to the conclusion it doesn't happen to all servers, most likely to due with arch/binary, for example on vanilla etded at debian based Linux I could reproduce this error 10 out of 10 tries on a ettv binary however I think this problem doesn't occur (courtesy of @msh100). So I think best option would be to add the fix just to be on the safe side, it has no downside to it therefore I think it would be a proper addition.
