### ISSUE TITLE
Missile_b3 glitch

### ISSUE THREAD

**Issue by Sebhes** [msh100/ETPro-configs#3]
Missile_b3 is the official version used these days in tournaments and cups. You might wonder why b4 isn't used, that is because the last stage is even more impossible to attack than in the 3rd stage.

There is one huge glitch in missile_b3 which needs to be fixed. After the allied have conquered the first stage and have successfully destroyed the door controls, they have to build the cp and/or steal the objective and secure this to a transmitter near the axis spawn. 

After the allied have successfully secured the objective, the axis can be trapped within their spawn for 5 to 10 seconds (not sure the exact time). This is, because the back door in the axis spawn, which leads to the last stage, is blocked and only opens after some waiting. 

This can ruin the entire map for the defending team. The last stage is generally known as the stage which is the stage the be defended the easiest. Attacking teams make use (abuse) of this glitch and it happened to me more than ones that I have lost the map because of this. 

I would like to have your thoughts about this issue. It would be great to have this solved.

**Comment by Sebhes** [comment]
Before the objective is secured, the door can still be opened by the axis. After the securing, the door should be completely open for both axis and allied teams. This is also the case, but only 5 to 10 seconds after the objective has been secured. The glitch should be lying with these 2 processes which mess things up.

**Comment by msh100** [comment]
`axisonlydoor2`

**Comment by Sebhes** [comment]
This should be fixed asap. Last 3 times I played missile_b3, I got 3 times faced with this ridiculous bug. 
Missile_b3 is a great map, would be even greater without this bug. However, I have no clue whether this is a time consuming process.

**Comment by Swanidius** [comment]
Really easy. The fix is in this config: https://www.dropbox.com/s/r1vs2voztytwvve/missile_b3.script?dl=0
(Made by hazz)

**Comment by Sebhes** [comment]
Good effort. What does it require to get this potentially implemented? Do we need to test it first?

**Comment by msh100** [comment]
This doesn't particularly need extensive testing. I have seen the mapscript and the bug is quite obvious, we just need to reorder the command and make sure what we expect to happen, happens. I can commit a change later tonight and we can see how that goes.
