### ISSUE TITLE
Increasing allowance of max FPS

### ISSUE THREAD

**Issue by triwats** [msh100/ETPro-configs#32]
It's 2016, and the historic 125 limit was to stop some players have a insane advantage of 333 FPS when some players were struggling to reach 76. That has now changed, and it is likely that atleast 80%+ of what is left of the ET community can now reach a stable value higher than 125. 

Additionally, the time of CRTs as the king for all FPS players is over, and have been replaced with monitors that now use '144hz' as their highest refresh rate value, sometimes even recommended value

I am suggesting we change max fps value to allow for these new gaming monitor standard, but am open to suggestions as to what the final value should be. It would be good to do it now, before the new LAN

166 would be a number that I see as sensible

**Comment by msh100** [comment]
Refer to #1 and #7
