### ISSUE TITLE
supply pause bug

### ISSUE THREAD

**Issue by Swanidius** [msh100/ETPro-configs#4]
crane moves when game pause in supply

**Comment by Sebhes** [comment]
Same for goldrush tank, while destroying bank. Link: #5

**Comment by msh100** [comment]
One potential way (as suggested by Micha) is to disable pauses during the long periods of `wait`'s in mapscripts. This isn't ideal but blocks abuse. Opinions?

fyi, this is easy to implement.

@Swanidius @Sebhes @ohurcool

**Comment by ohurcool** [comment]
If it's only during the movement of the crane on supply and while the tank is destroying the bank wall on grush, then I don't see why not as no one purposely pauses at those times anyway.

**Comment by msh100** [comment]
The only downside I can see is if someone has legitimately timed out.

But as it stands I guess it is against league rules to pause there anyway.

**Comment by ohurcool** [comment]
The "no-pause zone" would only be like 10 seconds or so, and any pause during that time is usually considered to be intentionally malicious anyway.

**Comment by msh100** [comment]
So to be clear, you're in favour of this?

**Comment by ohurcool** [comment]
Yep, works for me.

**Comment by ohurcool** [comment]
What will happen if you try pausing during these periods then? Is there a message?

**Comment by msh100** [comment]
There's a message in the console saying it's forbidden at this period in the map.

Sent from my iPhone

On 18 May 2015, at 00:41, ohurcool <notifications@github.com<mailto:notifications@github.com>> wrote:

What will happen if you try pausing during these periods then? Is there a message?

##

**Comment by ohurcool** [comment]
ok cool
